{% set name = "xnvme" %}
{% set libname = "libxnvme" %}
{% set version = "0.7.5" %}

package:
  name: {{ libname|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: "d951a3115f686956f5c6b839b390ffb50bb443f7711fe35f57a07f4d0667277f"

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - meson
    - ninja
    - pkg-config

  host:
    - libaio  # [linux]
    - liburing  # [linux]

about:
  home: https://xnvme.io/
  summary: Tools and libraries for efficient I/O
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  doc_url: https://xnvme.io/
  dev_url: https://github.com/xnvme/xnvme

extra:
  recipe-maintainers:
    - safl
